server:
  port: 8081

spring:
  application:
    name: aadhaar-service   # 🔁 Replace with your service name (e.g., aadhar-service)

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Gunjanbhawsar1@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
