server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aadhaar
    username: root
    password: Gunjanbhawsar1@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true